// dummy ride data
export default [
  {
    uid: "foo1",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo2",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo3",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo4",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo5",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo6",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo7",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo8",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
  {
    uid: "foo9",
    departureLocation: "Grinnell College",
    departureDateTime: new Date(),
    arrivalLocation: "Walmart",
    arrivalDateTime: new Date(),
  },
]
