// dummy ride data
export default [
  {
    id: "foo1",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo2",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo3",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo4",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo5",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo6",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo7",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo8",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
  {
    id: "foo9",
    departLocation: "Grinnell College",
    departDateTime: new Date(),
    arriveLocation: "Walmart",
    arriveDateTime: new Date(),
  },
]
